products = [
  {
    "_id": "1",
    "name": "Omeprazole",
    "image": "/images/sample.png",
    "description": "for peptic ulcer disease",
    "brand": "allDrugs",
    "category": "Antiulcer",
    "price": 2000,
    "countInStock": 0,
    "rating": 4.5,
    "numReviews": 11,
  },
  {
    "_id": "2",
    "name": "Amoxicillin",
    "image": "/images/amoxicillin.png",
    "description": "for bacterial infections",
    "brand": "allDrugs",
    "category": "Antibiotics",
    "price": 1500,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "3",
    "name": "Abacavir",
    "image": "/images/abacavir.png",
    "description": "for viral infections",
    "brand": "allDrugs",
    "category": "Antivirals",
    "price": 1500,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "4",
    "name": "Acyclovir",
    "image": "/images/acyclovir.png",
    "description": "for viral infections",
    "brand": "allDrugs",
    "category": "Antivirals",
    "price": 1500,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "5",
    "name": "Cefdinir",
    "image": "/images/cefdinir.png",
    "description": "for bacterial infections",
    "brand": "allDrugs",
    "category": "Antibiotics",
    "price": 1500,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "6",
    "name": "Doxycycline",
    "image": "/images/doxycycline.png",
    "description": "for bacterial infections",
    "brand": "allDrugs",
    "category": "Antibiotics",
    "price": 1500,
    "countInStock": 10,
    "rating": 5,
    "numReviews": 12,
  },
  {
    "_id": "7",
    "name": "Lamivudine",
    "image": "/images/lamivudine.png",
    "description": "for viral infections",
    "brand": "allDrugs",
    "category": "Antivirals",
    "price": 1500,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "8",
    "name": "Loperamide",
    "image": "/images/loperamide.png",
    "description": "for gastroenteritic hyperactivity",
    "brand": "allDrugs",
    "category": "Antidiarrheals",
    "price": 1500,
    "countInStock": 10,
    "rating": 5,
    "numReviews": 12,
  },
  {
    "_id": "9",
    "name": "Piriton",
    "image": "/images/piriton.png",
    "description": "for allergy reactions",
    "brand": "allDrugs",
    "category": "Antihistamines",
    "price": 1500,
    "countInStock": 10,
    "rating": 4.5,
    "numReviews": 12,
  },
  {
    "_id": "10",
    "name": "Paracetamol",
    "image": "/images/paracetamol.png",
    "description": "for pain and inflammation",
    "brand": "allDrugs",
    "category": "Analgesics",
    "price": 1500,
    "countInStock": 10,
    "rating": 4.0,
    "numReviews": 12,
  },
]
